JAVAC=javac
sources = $(wildcard *.java)
classes = $(sources:.java=.class)

all: HelloWorld

HelloWorld: $(classes)

clean :
    rm -f *.class

%.class : %.java
    $(JAVAC) $<

jar: $(classes)
    jar cvf HelloWorld.jar $(classes) 